### ISSUE TITLE
Getting "no matching action clause to process request" when trying to create via email

### ISSUE THREAD

**Issue by iamjaylee** [ylankgz/shlack#1]
When trying to create a user via email, I'm hitting a *\* bad request to Shlack.AuthController.callback, no matching action clause to process request**.

Did a git clone of the repo as well and still hitting that error.

**Comment by ylankgz** [comment]
Are your deps compiling properly? And also did you create `dev.secret.exs` file? Provide your console output

**Comment by iamjaylee** [comment]
Ah, you can close. Typo when spelling identity.
